[package]
name = "my_users_app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = {version = "0.5.0-rc.3", features = ["json", "secrets"]}
sqlite = "0.30.4"
yew = "0.20"